PANDAS

In [26]:
import pandas as pd

CREATING DATAFRAMES

In [4]:
data={'patient':['001','002','003','004','005'],
     'age':[22,30,15,7,42],
      'sex':['male','male','female','male','female'],
      'blood_group':['A+','B+','O+','B-','O+'],
     'glucose':[3.2,5.5,4.1,7.2,3.5]}
patient_data= pd.DataFrame(data)
patient_data

  patient  age     sex blood_group  glucose
0     001   22    male          A+      3.2
1     002   30    male          B+      5.5
2     003   15  female          O+      4.1
3     004    7    male          B-      7.2
4     005   42  female          O+      3.5

In [5]:
data2={'patient_id':['LB1','LB2','LB3','LB4','LB5','LB6','LB7','LB8','LB9','LB10','LB11','LB12','LB13','LB14','LB15'],
      'age':[25,34,12,16,54,43,44,28,39,27,51,52,42,36,15],
      'sex':['male','female','female','female','male','male','female','female','male','female','female','female','male','male','male'],
      'genotype':['AA','AS','AA','AA','SS','AS','AA','AA','AS','AS','AA','AS','AA','AS','AA'],
      'blood_group':['A+','B+','O+','B-','O+','O-','B+','AB+','A+','A-','B-','O+','O+','O+','B+'],
      'glucose':[5.5,2.9,3.8,4.4,12.2,3.2,5.5,4.1,7.2,3.5,6.7,7.4,3.5,2.8,7.1],
      'pcv':[33,38,35,44,52,40,28,22,28,39,43,45,19,39,21]}
record=pd.DataFrame(data2)
record

   patient_id  age     sex genotype blood_group  glucose  pcv
0         LB1   25    male       AA          A+      5.5   33
1         LB2   34  female       AS          B+      2.9   38
2         LB3   12  female       AA          O+      3.8   35
3         LB4   16  female       AA          B-      4.4   44
4         LB5   54    male       SS          O+     12.2   52
5         LB6   43    male       AS          O-      3.2   40
6         LB7   44  female       AA          B+      5.5   28
7         LB8   28  female       AA         AB+      4.1   22
8         LB9   39    male       AS          A+      7.2   28
9        LB10   27  female       AS          A-      3.5   39
10       LB11   51  female       AA          B-      6.7   43
11       LB12   52  female       AS          O+      7.4   45
12       LB13   42    male       AA          O+      3.5   19
13       LB14   36    male       AS          O+      2.8   39
14       LB15   15    male       AA          B+      7.1   21

READ IN EXCEL AND CSV FILES

In [10]:
healthcare=pd.read_csv('C:/Users/Khaled/Documents/healthcare_dataset.csv')
healthcare

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [11]:
healthcare.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [12]:
healthcare.tail()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [13]:
blood_transfusion=pd.read_csv('C:/Users/Khaled/Documents/transfusion.csv')
blood_transfusion

,Recency (months),Frequency (times),Monetary (c.c. blood),Time (months),whether he/she donated blood in March 2007
0,2,50,12500,98,1
1,0,13,3250,28,1
2,1,16,4000,35,1
3,2,20,5000,45,1
4,1,24,6000,77,0
...,...,...,...,...,...
743,23,2,500,38,0
744,21,2,500,52,0
745,23,3,750,62,0
746,39,1,250,39,0
747,72,1,250,72,0

In [14]:
blood_transfusion.head()

,Recency (months),Frequency (times),Monetary (c.c. blood),Time (months),whether he/she donated blood in March 2007
0,2,50,12500,98,1
1,0,13,3250,28,1
2,1,16,4000,35,1
3,2,20,5000,45,1
4,1,24,6000,77,0

In [15]:
blood_transfusion.tail()

,Recency (months),Frequency (times),Monetary (c.c. blood),Time (months),whether he/she donated blood in March 2007
743,23,2,500,38,0
744,21,2,500,52,0
745,23,3,750,62,0
746,39,1,250,39,0
747,72,1,250,72,0

In [18]:
healthcare.info()

<class 'pandas.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  str
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  str
 3   Blood Type          55500 non-null  str
 4   Medical Condition   55500 non-null  str
 5   Date of Admission   55500 non-null  str
 6   Doctor              55500 non-null  str
 7   Hospital            55500 non-null  str
 8   Insurance Provider  55500 non-null  str
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  str
 12  Discharge Date      55500 non-null  str
 13  Medication          55500 non-null  str
 14  Test Results        55500 non-null  str
dtypes: float64(1), int64(2), str(12)
memory usage: 12.3 MB

In [19]:
healthcare.describe()

                Age  Billing Amount   Room Number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224652    202.000000
50%       52.000000    25538.069376    302.000000
75%       68.000000    37820.508436    401.000000
max       89.000000    52764.276736    500.000000

In [22]:
healthcare.keys()

Index(['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition',
       'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider',
       'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date',
       'Medication', 'Test Results'],
      dtype='str')

In [25]:
healthcare.value_counts()

Name               Age  Gender  Blood Type  Medical Condition  Date of Admission  Doctor             Hospital                      Insurance Provider  Billing Amount  Room Number  Admission Type  Discharge Date  Medication  Test Results
Nancy glOVeR       58   Male    A-          Hypertension       2020-05-08         Jennifer Larson    Khan, and Rodriguez Fischer   Medicare            19183.168885    378          Emergency       2020-06-01      Aspirin     Abnormal        2
DAVid higgInS      49   Female  B-          Arthritis          2021-03-05         Erin Henderson MD  Evans and Hall Schneider,     Medicare            24948.477824    361          Emergency       2021-03-20      Penicillin  Abnormal        2
RoBErt hIGGInS     42   Male    AB-         Asthma             2021-05-06         Scott Davis        and Ford Lee, Rodriguez       Medicare            13355.782085    451          Elective        2021-05-29      Ibuprofen   Inconclusive    2
kevIn HiCKs        66   Male    AB+         Arthritis          2021-06-23         Kelly Murphy       Robinson Inc                  Medicare            1897.891727     196          Elective        2021-07-09      Ibuprofen   Abnormal        2
miCHAeL TayloR     29   Male    O-          Asthma             2020-02-27         Erica Mccormick    Donaldson-Frey                Medicare            41939.119937    453          Elective        2020-03-26      Ibuprofen   Normal          2
                                                                                                                                                                                                                                               ..
eLIZABeTH jaCkSOn  42   Female  O+          Asthma             2020-08-16         Joshua Jarvis      Jones-Thompson                Blue Cross          2650.714952     417          Elective        2020-09-15      Penicillin  Abnormal        1
KYle pEREz         61   Female  AB-         Obesity            2020-01-23         Taylor Sullivan    Tucker-Moyer                  Cigna               31457.797307    316          Elective        2020-02-01      Aspirin     Normal          1
HEATher WaNG       38   Female  B+          Hypertension       2020-07-13         Joe Jacobs DVM     and Mahoney Johnson Vasquez,  UnitedHealthcare    27620.764717    347          Urgent          2020-08-10      Ibuprofen   Abnormal        1
JENniFER JOneS     43   Male    O-          Arthritis          2019-05-25         Kimberly Curry     Jackson Todd and Castro,      Medicare            32451.092358    321          Elective        2019-05-31      Ibuprofen   Abnormal        1
jAMES GARCiA       53   Female  O+          Arthritis          2024-04-02         Dennis Warren      Henry Sons and                Aetna               4010.134172     448          Urgent          2024-04-29      Ibuprofen   Abnormal        1
Name: count, Length: 54966, dtype: int64

In [29]:
healthcare.isna().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [27]:
blood_transfusion.info()

<class 'pandas.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 5 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Recency (months)                            748 non-null    int64
 1   Frequency (times)                           748 non-null    int64
 2   Monetary (c.c. blood)                       748 non-null    int64
 3   Time (months)                               748 non-null    int64
 4   whether he/she donated blood in March 2007  748 non-null    int64
dtypes: int64(5)
memory usage: 29.3 KB

In [30]:
blood_transfusion.describe()

,Recency (months),Frequency (times),Monetary (c.c. blood),Time (months),whether he/she donated blood in March 2007
count,748.000000,748.000000,748.000000,748.000000,748.000000
mean,9.506684,5.514706,1378.676471,34.282086,0.237968
std,8.095396,5.839307,1459.826781,24.376714,0.426124
min,0.000000,1.000000,250.000000,2.000000,0.000000
25%,2.750000,2.000000,500.000000,16.000000,0.000000
50%,7.000000,4.000000,1000.000000,28.000000,0.000000
75%,14.000000,7.000000,1750.000000,50.000000,0.000000
max,74.000000,50.000000,12500.000000,98.000000,1.000000

In [31]:
blood_transfusion.keys()

Index(['Recency (months)', 'Frequency (times)', 'Monetary (c.c. blood)',
       'Time (months)', 'whether he/she donated blood in March 2007'],
      dtype='str')

In [32]:
blood_transfusion.value_counts()

Recency (months)  Frequency (times)  Monetary (c.c. blood)  Time (months)  whether he/she donated blood in March 2007
2                 1                  250                    2              0                                             27
4                 1                  250                    4              0                                             27
16                1                  250                    16             0                                             17
14                1                  250                    14             0                                             16
21                1                  250                    21             0                                             15
                                                                                                                         ..
23                2                  500                    38             0                                              1
21                2                  500                    52             0                                              1
23                3                  750                    62             0                                              1
39                1                  250                    39             0                                              1
72                1                  250                    72             0                                              1
Name: count, Length: 533, dtype: int64

Selecting and Filtering Data

In [41]:
above30=healthcare[healthcare['Age']>30]
above30.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
5,EMILY JOHNSOn,36,Male,A+,Asthma,2023-12-20,Taylor Newton,Nunez-Humphrey,UnitedHealthcare,48145.110951,389,Urgent,2023-12-24,Ibuprofen,Normal
8,JASmINe aGuIlaR,82,Male,AB+,Asthma,2020-07-01,Daniel Ferguson,Sons Rich and,Cigna,50119.222792,316,Elective,2020-07-14,Aspirin,Abnormal

In [38]:
above30.info()

<class 'pandas.DataFrame'>
Index: 45001 entries, 1 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                45001 non-null  str
 1   Age                 45001 non-null  int64
 2   Gender              45001 non-null  str
 3   Blood Type          45001 non-null  str
 4   Medical Condition   45001 non-null  str
 5   Date of Admission   45001 non-null  str
 6   Doctor              45001 non-null  str
 7   Hospital            45001 non-null  str
 8   Insurance Provider  45001 non-null  str
 9   Billing Amount      45001 non-null  float64
 10  Room Number         45001 non-null  int64
 11  Admission Type      45001 non-null  str
 12  Discharge Date      45001 non-null  str
 13  Medication          45001 non-null  str
 14  Test Results        45001 non-null  str
dtypes: float64(1), int64(2), str(12)
memory usage: 10.4 MB

In [44]:
above30.describe()

                Age  Billing Amount   Room Number
count  45001.000000    45001.000000  45001.000000
mean      57.984889    25516.551361    301.035999
std       15.840216    14213.178229    115.328150
min       31.000000    -2008.492140    101.000000
25%       44.000000    13202.481834    202.000000
50%       58.000000    25544.675144    302.000000
75%       72.000000    37803.584498    401.000000
max       89.000000    52764.276736    500.000000

In [42]:
under30=healthcare[healthcare['Age']<30]
under30.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
6,edwArD EDWaRDs,21,Female,AB-,Diabetes,2020-11-03,Kelly Olson,Group Middleton,Medicare,19580.872345,389,Emergency,2020-11-15,Paracetamol,Inconclusive
7,CHrisTInA MARtinez,20,Female,A+,Cancer,2021-12-28,Suzanne Thomas,"Powell Robinson and Valdez,",Cigna,45820.462722,277,Emergency,2022-01-07,Paracetamol,Inconclusive
31,JAmES pattERson,23,Female,A+,Arthritis,2019-11-03,Kristina Frazier,Cruz-Santiago,UnitedHealthcare,25835.323595,108,Urgent,2019-11-29,Penicillin,Abnormal
35,DAvID AndErSON,25,Female,AB+,Asthma,2021-01-07,Emma Allison,Sons and Cox,Medicare,45453.418546,228,Elective,2021-01-26,Lipitor,Abnormal

In [43]:
under30.info()

<class 'pandas.DataFrame'>
Index: 9693 entries, 3 to 55483
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                9693 non-null   str
 1   Age                 9693 non-null   int64
 2   Gender              9693 non-null   str
 3   Blood Type          9693 non-null   str
 4   Medical Condition   9693 non-null   str
 5   Date of Admission   9693 non-null   str
 6   Doctor              9693 non-null   str
 7   Hospital            9693 non-null   str
 8   Insurance Provider  9693 non-null   str
 9   Billing Amount      9693 non-null   float64
 10  Room Number         9693 non-null   int64
 11  Admission Type      9693 non-null   str
 12  Discharge Date      9693 non-null   str
 13  Medication          9693 non-null   str
 14  Test Results        9693 non-null   str
dtypes: float64(1), int64(2), str(12)
memory usage: 2.2 MB

In [45]:
under30.describe()

               Age  Billing Amount  Room Number
count  9693.000000     9693.000000  9693.000000
mean     23.406788    25578.681223   301.476014
std       3.516265    14211.712771   114.664681
min      13.000000    -1277.645337   101.000000
25%      20.000000    13359.863233   204.000000
50%      23.000000    25411.077284   302.000000
75%      26.000000    37712.075071   399.000000
max      29.000000    52271.663747   500.000000

In [50]:
healthcare['Blood Type']

0         B-
1         A+
2         A-
3         O+
4        AB+
        ...
55495     O+
55496    AB-
55497     B+
55498     O-
55499     O+
Name: Blood Type, Length: 55500, dtype: str

In [51]:
healthcare['Hospital']

0                     Sons and Miller
1                             Kim Inc
2                            Cook PLC
3          Hernandez Rogers and Vang,
4                         White-White
                     ...
55495                  Jones-Thompson
55496                    Tucker-Moyer
55497    and Mahoney Johnson Vasquez,
55498        Jackson Todd and Castro,
55499                  Henry Sons and
Name: Hospital, Length: 55500, dtype: str

In [59]:
healthcare['Medication']

0        Paracetamol
1          Ibuprofen
2            Aspirin
3          Ibuprofen
4         Penicillin
            ...
55495     Penicillin
55496        Aspirin
55497      Ibuprofen
55498      Ibuprofen
55499      Ibuprofen
Name: Medication, Length: 55500, dtype: str

In [60]:
healthcare['Insurance Provider']

0              Blue Cross
1                Medicare
2                   Aetna
3                Medicare
4                   Aetna
               ...
55495          Blue Cross
55496               Cigna
55497    UnitedHealthcare
55498            Medicare
55499               Aetna
Name: Insurance Provider, Length: 55500, dtype: str

In [49]:
healthcare['Medical Condition']

0              Cancer
1             Obesity
2             Obesity
3            Diabetes
4              Cancer
             ...
55495          Asthma
55496         Obesity
55497    Hypertension
55498       Arthritis
55499       Arthritis
Name: Medical Condition, Length: 55500, dtype: str

In [48]:
diabetes=healthcare[healthcare['Medical Condition']=='Diabetes']
diabetes.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
6,edwArD EDWaRDs,21,Female,AB-,Diabetes,2020-11-03,Kelly Olson,Group Middleton,Medicare,19580.872345,389,Emergency,2020-11-15,Paracetamol,Inconclusive
12,connOR HANsEn,75,Female,A+,Diabetes,2019-12-12,Kenneth Fletcher,"Powers Miller, and Flores",Cigna,43282.283358,134,Emergency,2019-12-28,Penicillin,Abnormal
27,mr. KenNEth MoORE,34,Female,A+,Diabetes,2022-06-21,James Ellis,Serrano-Dixon,UnitedHealthcare,18834.801341,157,Emergency,2022-06-30,Lipitor,Abnormal
34,NicOlE RodriGUEz,30,Female,AB+,Diabetes,2020-01-17,Lynn Young,Poole Inc,Blue Cross,8408.949354,285,Emergency,2020-02-10,Lipitor,Normal

Data Cleaning Basics

In [ ]:
df.isnull()

df.dropna()

df.fillna()

In [61]:
healthcare.isnull()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55496,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55497,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55498,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55499,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [63]:
healthcare.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [62]:
blood_transfusion.isna()

,Recency (months),Frequency (times),Monetary (c.c. blood),Time (months),whether he/she donated blood in March 2007
0,False,False,False,False,False
1,False,False,False,False,False
2,False,False,False,False,False
3,False,False,False,False,False
4,False,False,False,False,False
...,...,...,...,...,...
743,False,False,False,False,False
744,False,False,False,False,False
745,False,False,False,False,False
746,False,False,False,False,False
747,False,False,False,False,False

In [64]:
blood_transfusion.isna().sum()

Recency (months)                              0
Frequency (times)                             0
Monetary (c.c. blood)                         0
Time (months)                                 0
whether he/she donated blood in March 2007    0
dtype: int64

In [65]:
healthcare.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
55495    False
55496    False
55497    False
55498    False
55499    False
Length: 55500, dtype: bool

In [66]:
blood_transfusion.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
743    False
744    False
745    False
746    False
747    False
Length: 748, dtype: bool

In [78]:
data3={'patient_id':['LB1','LB2','LB3','LB4','LB5','LB6','LB7','LB8','LB9','LB10','LB11','LB12','LB13','LB14','LB15','LB1','LB2','LB3','LB4','LB5','LB6','LB7','LB8','LB9','LB10','LB11','LB12','LB13','LB14','LB15'],
      'age':[25,34,12,16,54,43,44,28,39,27,51,52,42,36,15,25,34,12,16,54,43,44,28,39,27,51,52,42,36,15],
      'sex':['male','female','female','female','male','male','female','female','male','female','female','female','male','male','male','male','female','female','female','male','male','female','female','male','female','female','female','male','male','male'],
      'genotype':['AA','AS','AA','AA','SS','AS','AA','AA','AS','AS','AA','AS','AA','AS','AA','AA','AS','AA','AA','SS','AS','AA','AA','AS','AS','AA','AS','AA','AS','AA'],
      'blood_group':['A+','B+','O+','B-','O+','O-','B+','AB+','A+','A-','B-','O+','O+','O+','B+','A+','B+','O+','B-','O+','O-','B+','AB+','A+','A-','B-','O+','O+','O+','B+'],
      'glucose':[5.5,2.9,3.8,4.4,12.2,3.2,5.5,4.1,7.2,3.5,6.7,7.4,3.5,2.8,7.1,5.5,2.9,3.8,4.4,12.2,3.2,5.5,4.1,7.2,3.5,6.7,7.4,3.5,2.8,7.1],
      'pcv':[33,38,35,44,52,40,28,22,28,39,43,45,19,39,21,33,38,35,44,52,40,28,22,28,39,43,45,19,39,21]}
record2=pd.DataFrame(data3)
record2.head()

  patient_id  age     sex genotype blood_group  glucose  pcv
0        LB1   25    male       AA          A+      5.5   33
1        LB2   34  female       AS          B+      2.9   38
2        LB3   12  female       AA          O+      3.8   35
3        LB4   16  female       AA          B-      4.4   44
4        LB5   54    male       SS          O+     12.2   52

In [79]:
record2.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   patient_id   30 non-null     str
 1   age          30 non-null     int64
 2   sex          30 non-null     str
 3   genotype     30 non-null     str
 4   blood_group  30 non-null     str
 5   glucose      30 non-null     float64
 6   pcv          30 non-null     int64
dtypes: float64(1), int64(2), str(4)
memory usage: 2.1 KB

In [80]:
record2.describe()

             age    glucose        pcv
count  30.000000  30.000000  30.000000
mean   34.533333   5.320000  35.066667
std    13.436269   2.467779   9.551795
min    12.000000   2.800000  19.000000
25%    25.500000   3.500000  28.000000
50%    36.000000   4.400000  38.000000
75%    43.750000   7.000000  42.250000
max    54.000000  12.200000  52.000000

In [81]:
record2.isna().sum()

patient_id     0
age            0
sex            0
genotype       0
blood_group    0
glucose        0
pcv            0
dtype: int64

In [83]:
record2.duplicated().sum()

np.int64(15)

In [88]:
record2.drop_duplicates(inplace=True)
record2

   patient_id  age     sex genotype blood_group  glucose  pcv
0         LB1   25    male       AA          A+      5.5   33
1         LB2   34  female       AS          B+      2.9   38
2         LB3   12  female       AA          O+      3.8   35
3         LB4   16  female       AA          B-      4.4   44
4         LB5   54    male       SS          O+     12.2   52
5         LB6   43    male       AS          O-      3.2   40
6         LB7   44  female       AA          B+      5.5   28
7         LB8   28  female       AA         AB+      4.1   22
8         LB9   39    male       AS          A+      7.2   28
9        LB10   27  female       AS          A-      3.5   39
10       LB11   51  female       AA          B-      6.7   43
11       LB12   52  female       AS          O+      7.4   45
12       LB13   42    male       AA          O+      3.5   19
13       LB14   36    male       AS          O+      2.8   39
14       LB15   15    male       AA          B+      7.1   21

In [89]:
record2.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
dtype: bool

Sorting and Grouping

In [94]:
healthcare.sort_values("Age")

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
53528,eLIzABETh cAsTILlO,13,Male,AB-,Hypertension,2021-01-03,Dawn Williams,Thomas-Pierce,Aetna,32900.044478,176,Elective,2021-01-27,Aspirin,Abnormal
50377,jamES BasS phD,13,Male,O+,Asthma,2020-12-30,Jennifer Hammond,"Pollard Wallace, Sims and",Blue Cross,22901.022707,476,Emergency,2021-01-17,Ibuprofen,Inconclusive
50823,DEaNnA pALMeR,13,Male,AB-,Obesity,2020-09-20,Barbara Butler,"and Sanchez Phillips, Brown",Medicare,23941.759486,163,Emergency,2020-09-23,Penicillin,Inconclusive
52172,CHArlEs joRDAN,13,Male,A+,Arthritis,2021-05-13,Brian Baker,"Arellano and Armstrong Hensley,",UnitedHealthcare,10597.383799,451,Emergency,2021-06-12,Penicillin,Normal
51095,cAthY BARNES,13,Male,O-,Obesity,2023-03-30,Kevin Ellison,Wood-Johnson,Medicare,29170.617795,348,Emergency,2023-04-29,Lipitor,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52857,THomAs PHIllIpS,89,Female,A+,Hypertension,2022-05-22,Mark White,"and Martin, Davidson Cox",Cigna,48274.348627,332,Urgent,2022-05-26,Penicillin,Inconclusive
52043,DAVId NeWTOn,89,Female,O+,Arthritis,2021-02-08,Jerry Hopkins,"Cooper Brown Parks, and",Aetna,34500.016817,242,Elective,2021-02-20,Penicillin,Inconclusive
54044,MiChAEL DOmINGuEz,89,Male,O+,Cancer,2021-09-07,Bridget Irwin,PLC White,Aetna,7628.951322,363,Elective,2021-09-24,Aspirin,Abnormal
52828,doNALD aViLA,89,Female,AB-,Asthma,2022-09-17,Christopher Allen,"Holmes and Howard Castro,",Aetna,14042.748908,199,Emergency,2022-09-27,Aspirin,Abnormal
52372,DeBORah McBrIdE,89,Female,O+,Obesity,2021-05-28,Robert Garcia,"and Miller, Olson Olson",Cigna,5692.907188,166,Elective,2021-06-13,Paracetamol,Abnormal

In [100]:
healthcare.groupby("Gender").count()

,Name,Age,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
Gender,,,,,,,,,,,,,,
Female,27726,27726,27726,27726,27726,27726,27726,27726,27726,27726,27726,27726,27726,27726
Male,27774,27774,27774,27774,27774,27774,27774,27774,27774,27774,27774,27774,27774,27774

In [101]:
healthcare.groupby("Gender").mean(numeric_only=True)

              Age  Billing Amount  Room Number
Gender
Female  51.578735    25470.652958   301.865181
Male    51.500252    25607.860571   300.405739

In [102]:
healthcare.groupby("Gender")["Billing Amount"].mean()

Gender
Female    25470.652958
Male      25607.860571
Name: Billing Amount, dtype: float64

In [104]:
healthcare.groupby("Gender")["Age"].mean()

Gender
Female    51.578735
Male      51.500252
Name: Age, dtype: float64

In [105]:
healthcare.groupby("Gender")["Billing Amount"].agg(['mean', 'min', 'max'])

                mean          min           max
Gender
Female  25470.652958 -2008.492140  52764.276736
Male    25607.860571 -1660.009373  52271.663747